[build-system]
requires = [
  "setuptools>=69",
  "wheel",
  "cmake>=3.20",
  "patchelf>=0.17.2.1; platform_system == 'Linux'"  # provides the patchelf binary on Linux
]
build-backend = "setuptools.build_meta"

[project]
name = "sirius-bio"
version = "1.7"
description = "SIRIUS: maximally divergent synonymous gene design with ILP/CP-SAT core "
authors = [{ name = "Amirsadra Mohseni", email = "amohs002@ucr.edu" }]
requires-python = ">=3.10"
readme = "pypi_README.md"
license = { file = "LICENSE" }

[project.scripts]
sirius = "sirius.sirius_wrapper:main"

[tool.setuptools.packages.find]
where = ["python"]
include = ["sirius*"]

[tool.setuptools.package-data]
"sirius" = ["build/sirius", "resources/py27_env.tar.xz"]
"sirius.GeneDiversifier" = ["*.py", "data/*.csv"]
